
FROM golang:1.24 AS builder
WORKDIR /src
COPY ./main.go .
ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
RUN go build -o hello ./main.go
FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /src/hello /app/hello
CMD ["/app/hello"]


